name: Test Build
on:
  pull_request:
jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - id: set
        run: |
          echo "::set-output name=run_job_b::no"
    outputs:
      run_job_b: ${{ steps.set.outputs.run_job_b }}
  b:
    name: b
    runs-on: ubuntu-latest
    needs: [a]
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    steps:
      - run: exit 1
  c:
    name: c
    runs-on: ubuntu-latest
    if: always() # always run, so we never skip the check
    needs: [b]
    steps:
      # https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
      - name: Check status
        run: |
          passed="${{ (needs.unit-test.result == 'success' || (needs.unit-test.result == 'skipped' && contains(github.event.pull_request.labels.*.name, 'dependencies')))  }}"
          if [[ $passed == "true" ]]; then
            echo "Shards passed"
            exit 0
          else
            echo "Shards failed"
            exit 1
          fi
      - name: Print echo
        run: echo "CC"
