name: Sonarqube Trigger

on:
  workflow_dispatch:

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check git status
        shell: bash
        run: |
          git status
